# dm Aln

### GROUPE
- Yue Sheng
- Younoussa Sow

### Méthode de Newton en une variable

In [3]:
import numpy as np
import scipy as cpi
import math
import sympy as sp

#### Question 1
Cela permet de trouver la racine négative.

En effet, la fonction `f(x) = x^2 - 4` admet deux racines réels `-2`  et `2`
avec une première approximation de:
 - `u[0] > 0` on obtient la racine positive
 - `u[0] < 0` on obtient la racine négative

In [59]:
def f(x):
#    return (x - 2)**2
    return x**2 - 3

#### Quesiton 2
En effet, on doit avoir le resultat `2`. Mais, ça donne un resultat légerement different `2.0312500`.
Parce que `a = 3` est beaucoup plus grand que `2`, et la `limite = 5` n'est pas suffisante pour trouver la bonne valeur.
Il faut donc choisir une limite plus grande pour affiner le resultat, par exemple `limite = 52`, nous donne le bon resultat.
Ou choisir une première approximation plus proche de 2 qui permettra de trouver avec une plus petite limite le bon resultat.

In [60]:
def df(x):
    #return 2*(x - 2)
    assert a > 0
    return 2*x

In [61]:
def tmp():
    global a
    global limit
    assert a > 0
    for i in range(limit):
        a = a  - f(a)/df(a)
        print('U_{:02d}: {:.40f}'.format(i+1, a))

In [62]:
a = 2
limit = 7
tmp()

U_01: 1.7500000000000000000000000000000000000000
U_02: 1.7321428571428572062984585500089451670647
U_03: 1.7320508100147276042690691610914655029774
U_04: 1.7320508075688771931766041234368458390236
U_05: 1.7320508075688774152212090484681539237499
U_06: 1.7320508075688771931766041234368458390236
U_07: 1.7320508075688774152212090484681539237499


### Méthode de Newton en deux variables

In [63]:
def f1(x, y):
    return x**2 + 2*x*y -1

def f2(x, y):
    return x**2*y**2 - y - 3

In [64]:
def df1x(x,y):
    return 2*x + 2*y

def df1y(x,y):
    return 2*x

def df2x(x,y):
    return 2*x*y**2

def df2y(x,y):
    return 2*x**2*y - 1

In [65]:
def eval(x, y):
    return f1(x,y), f2(x,y)

In [66]:
eval(x=2,y=-3/4)

(0.0, 0.0)

In [68]:
J = np.array([df1x(x,y),df1y(x,y)],[df2x(x,y),df2y(x,y)])

TypeError: data type not understood

In [20]:
import sympy as sp

In [21]:
x = Symbol("x")
y = Symbol("y")

In [22]:
f1 = x**2 + 2*x*y - 1
f2 = x**2*y**2 - y - 3

In [23]:
f1

x**2 + 2*x*y - 1

In [24]:
f2

x**2*y**2 - y - 3

In [25]:
df1x = sp.diff(f1, x)
df1y = sp.diff(f1, y)

df2x = sp.diff(f2, x)
df2y = sp.diff(f2, y)

In [26]:
df2x

2*x*y**2

In [27]:
a,b,x,y = sp.symbols("a b x y")
a = f1
b = f2
funcs = sp.Matrix([a,b])
args = sp.Matrix([x,y])
J = funcs.jacobian(args)

In [39]:
J

Matrix([
[2*x + 2*y,          2*x],
[ 2*x*y**2, 2*x**2*y - 1]])

In [42]:
J

TypeError: applyfunc() takes 2 positional arguments but 3 were given

In [7]:
def Newton(f, dfdx, x, eps):
    f_value = f(x)
    iteration_counter = 0
    while abs(f_value) > eps and iteration_counter < 100:
        try:
            x = x - float(f_value)/dfdx(x)
        except ZeroDivisionError:
            print(f"Error! - derivative zero for x = {x}")
            sys.exit(1)     # Abort with error

        f_value = f(x)
        iteration_counter += 1

    # Here, either a solution is found, or too many iterations
    if abs(f_value) > eps:
        iteration_counter = -1
    return x, iteration_counter

def f(x):
    #return x**2 - 9
    
def dfdx(x):
    return 2*x

solution, no_iterations = Newton(f, dfdx, x=1000, eps=1.0e-6)

if no_iterations > 0:    # Solution found
    print(f"Number of function calls: {1 + 2*no_iterations}")
    print(f"A solution is: {solution:.30f}")
else:
    print("Solution not found!")

Number of function calls: 25
A solution is: 3.000000000127320376464012952056


In [9]:
from sympy import *
x = symbols('x')             # define x as a mathematical symbol
f_expr = x**2 - 9            # symbolic expression for f(x)
dfdx_expr = diff(f_expr, x)  # compute f'(x) symbolically
# Turn f_expr and dfdx_expr into plain Python functions
f = lambdify([x],     # argument to f
             f_expr)  # symbolic expression to be evaluated
dfdx = lambdify([x], dfdx_expr)
print(dfdx(5))         # will print 10

10


In [16]:
dfdx(5)

10

In [17]:
u = np.array([3., -1])

In [18]:
for n in range(6):
    

array([ 3., -1.])

In [72]:
import numpy as np

def Newton_system(F, J, x, eps):
    """
    Solve nonlinear system F=0 by Newton's method.
    J is the Jacobian of F. Both F and J must be functions of x.
    At input, x holds the start value. The iteration continues
    until ||F|| < eps.
    """
    F_value = F(x)
    F_norm = np.linalg.norm(F_value, ord=2)  # l2 norm of vector
    iteration_counter = 0
    while abs(F_norm) > eps and iteration_counter < 100:
        delta = np.linalg.solve(J(x), -F_value)
        x = x + delta
        F_value = F(x)
        # print(F(x))
        # print(J(x))
        F_norm = np.linalg.norm(F_value, ord=2)
        iteration_counter += 1

    # Here, either a solution is found, or too many iterations
    if abs(F_norm) > eps:
        iteration_counter = -1
    return x, iteration_counter

In [73]:
def test_Newton_system1():
    def F(x):
        return np.array(
            [
                x[0]**2 - 2*x[0]*x[1] - 1,
                x[0]**2*x[1]**2 - x[1] - 3
            ]
        )
    
    def J(x):
        return np.array(
            [
                [2*x[0] + 2*x[1], 2*x[0]],
                [2*x[0]*x[1]**2,  2*x[0]**2*x[0] - 1]
            ]
        )

    # expected = np.array([1, 0])
    tol = 1e-4
    x, n = Newton_system(F, J, x=np.array([2, -1]), eps=0.0000000001)
    print(n)
    print(x)
    # error_norm = np.linalg.norm(expected - x, ord=2)
    # assert error_norm < tol, 'norm of error =%g' % error_norm
    # print(f"norm of error = {error_norm}")

In [74]:
test_Newton_system1()

[30.33163265  8.67898792]
[[  -8.42857143   -9.85714286]
 [  -5.02915452 -240.43804665]]
[ 2.37566229 -2.92613651]
[[-1.21762206 -2.5658779 ]
 [-1.16605925 -5.22326144]]
[31.61395972 29.40597371]
[[  6.84873923   9.26123463]
 [ 13.47540679 197.5851048 ]]
[-1.42209342 -1.91990564]
[[-2.51213378 -0.46534223]
 [-0.48737102 -1.0251917 ]]
[-3.40803458  1.51343855]
[[-6.50977423 -0.94605358]
 [-7.32126918 -1.2116836 ]]
[  456.32724257 43681.31184709]
[[ 5.43177386e+01 -1.25142396e+01]
 [-1.39737544e+04 -4.90951855e+02]]
[   736.17225225 127901.68101756]
[[ 1.44344084e+02 -9.31282641e+00]
 [-5.49699968e+04 -2.02922415e+02]]
[  1021.04036919 257153.78509756]
[[ 3.65959489e+02 -5.46320268e+00]
 [-1.88418780e+05 -4.17644838e+01]]
[  1314.29653678 430699.02982481]
[[ 9.17057293e+02 -2.85518146e+00]
 [-6.04041448e+05 -6.81890348e+00]]
[  1656.22997681 685020.74199661]
[[ 2.29216291e+03 -1.44463096e+00]
 [-1.89991926e+06 -1.75372126e+00]]
[   2079.54288524 1079161.49733803]
[[ 5.72496070e+03 -7.266